CREATE TABLE Aerzte_TBL
	(
	AID INT(11) NOT NULL AUTO_INCREMENT,
	FName VARCHAR(25),
	LName VARCHAR(25),
	Fach VARCHAR (25),
	EIdN INT(8),
	PRIMARY KEY (AID)
	)ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
	
CREATE TABLE Patient_TBL
	(
	PID INT (11) NOT NULL AUTO_INCREMENT,
	FName VARCHAR(25),
	LName VARCHAR(25),
	IdN INT(10),
	PRIMARY KEY(PID)
	)ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
	
CREATE TABLE Untersuchung_TBL
	(
	UntID INT(11) NOT NULL AUTO_INCREMENT,
	UntDate Date,
	AID INT(11),
	PID INT(11),
	PRIMARY KEY (UntID),
	FOREIGN KEY (AID) REFERENCES Aerzte_TBL(AID),
	FOREIGN KEY (PID) REFERENCES Patient_TBL(PID)
	)ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
	
	CREATE TABLE Diagnose_TBL
	(
	DID INT(11) NOT NULL AUTO_INCREMENT,
	UntID INT(11),
	Diagnose VARCHAR (35),
	PRIMARY KEY (DID),
	FOREIGN KEY (UntID) REFERENCES Untersuchung_TBL(UntID)
	)ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
	
CREATE TABLE Rezepte_TBL
	(
	RID INT(11) NOT NULL AUTO_INCREMENT,
	DID INT(11),
	Arznei VARCHAR(100),
	PRIMARY KEY (RID),
	FOREIGN KEY(DID) REFERENCES Diagnose_TBL(DID)
	)ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
	
	
INSERT INTO Aerzte_TBL(AID, FName, LName, Fach, EIdN) VALUES
(NULL, "Stoyan", "Dimitrov", "Allgemein", 98765432),
(NULL, "Aleksander", "Balabanov", "ONH", 12345678),
(NULL, 'Muncho', 'Veliki', 'Lungen', 13579246);
	
INSERT INTO Patient_TBL(PID, FName, LName, IdN) VALUES
(NULL, "Ivan", "Ivanov", 1234567890),
(NULL, "Stanka", "Zdravkova", 0987654321),
(NULL, "Pasho", "Pashov", 8765123402),
(NULL, "Georgi", "Georgiev", 8527419630);
	
INSERT INTO Untersuchung_TBL(UntID, UntDate, AID, PID) VALUES
(NULL, "2012-7-22", 1, 3),
(NULL, "2012-4-15", 3, 2),
(NULL, "2012-3-18", 2, 4),
(NULL, "2012-12-16", 1, 1);
	
INSERT INTO Diagnose_TBL(DID, UntID, Diagnose) VALUES
(NULL, 2,  "Bronchitis"),
(NULL, 3, "Angina");
	
INSERT INTO Rezepte_TBL(RID, DID, Arznei) VALUES
(NULL, 1, "Rakia mit Turschia"),
(NULL, 2, "Rakia mit Honig");

	
	
	